brew age
brew antidote
brew btop
brew chroma
brew cirruslabs/cli/tart
brew colima
brew coreutils
brew dnsmasq
brew docker
brew fzf
brew gemini-cli
brew gh
brew git
brew gnu-sed
brew gnupg
brew incus
brew jeffreywildman/virt-manager/virt-viewer
brew libiconv
brew lima-additional-guestagents
brew meson
brew mise
brew ncdu
brew pipx
brew protonpass/tap/pass-cli
brew python@3.13
brew ripgrep
brew rsync
brew rtk
brew sevenzip
brew topgrade
brew wget
brew wireguard-tools
brew yt-dlp
brew zsh-syntax-highlighting
cask 1password
cask antigravity
cask anytype
cask arq
cask balenaetcher
cask chromium
cask cryptomator
cask deezer
cask displaylink
cask espanso
cask firefox@developer-edition
cask gimp
cask google-chrome
cask google-drive
cask inkscape
cask iterm2
cask jetbrains-toolbox
cask logi-options+
cask notunes
cask nvidia-geforce-now
cask obsidian
cask proton-pass
cask protonvpn
cask raycast
cask remoteviewer
cask rustdesk
cask spotify
cask steam
cask tailscale-app
cask tor-browser
cask visual-studio-code
cask vlc
